# fly.toml app configuration file generated for full-stack-open-pokedex-lively-sound-9394 on 2025-05-12T21:07:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-lively-sound-9394'
primary_region = 'scl'

[build]

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  strategy = "canary"

[[vm]]
  size = 'shared-cpu-1x'
