name: Discord Test

on:
    push:
        branches:
            - exercise_11_18

jobs:
    main_job:
        runs-on: ubuntu-24.04
        steps:
            - run: "echo 'Hello World!'"
    notify_job:
        needs: [main_job]
        runs-on: ubuntu-24.04
        steps:
            - name: Test success message
              uses: sarisia/actions-status-discord@v1
              if: success()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{job.status}}
                  title: "deploy"
                  description: "New Release completed successfully"
                  color: 0x03fc1c
                  url: "https://github.com/gus25888/full-stack-open-pokedex/"
                  username: GitHub Action Result for ${{github.repository}}
            - name: Test error message
              uses: sarisia/actions-status-discord@v1
              if: failure()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{job.status}}
                  title: "deploy"
                  description: "New Release failed"
                  color: 0xfc0303
                  url: "https://github.com/gus25888/full-stack-open-pokedex/"
                  username: GitHub Action Result for ${{github.repository}}
            - name: Cancel Notification - Discord
              uses: sarisia/actions-status-discord@v1
              if: cancelled()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{job.status}}
                  title: "deploy"
                  description: "New Release cancelled"
                  color: 0x545151
                  url: "https://github.com/gus25888/full-stack-open-pokedex/"
                  username: GitHub Action Result for ${{github.repository}}
