name: Discord Test

on:
    push:
        branches:
            - exercise_11_18

jobs:
    notify_job:
        runs-on: ubuntu-24.04
        steps:
            - name: Test Success
              uses: rjstone/discord-webhook-notify@v1.0.4
              if: success()
              with:
                  severity: info
                  details: Test Succeeded!
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - name: Test Failure
              uses: rjstone/discord-webhook-notify@v1.0.4
              if: failure()
              with:
                  severity: error
                  details: Test Failed!
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - name: Test Cancelled
              uses: rjstone/discord-webhook-notify@v1.0.4
              if: cancelled()
              with:
                  severity: warn
                  details: Test Cancelled!
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
