name: Discord Test

on:
    push:
        branches:
            - exercise_11_18

jobs:
    notify_job:
        runs-on: ubuntu-24.04
        steps:
            - name: Test message
              uses: sarisia/actions-status-discord@v1
              if: always()
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{job.status}}
                  nodetail: true
                  title: "Deploy"
                  description: "New Release completed successfully"
                  color: 0x03fc1c
                  url: "https://github.com/gus25888/full-stack-open-pokedex/"
                  username: GitHub Action Result for ${{github.repository}}
