name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        name: Deploy app
        # Optional only deploy if it is a pull request approved
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-24.04
        concurrency: deploy-group # optional: ensure only one action runs at a time
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: npm ci
            - name: lint
              run: npm run eslint
            - name: build
              run: npm run build
            - name: test
              run: npm run test
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: e2e tests
              run: npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
            - run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    tag_release:
        if: ${{ github.event_name == 'push' }}
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.73.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAG_PREFIX: v
                  DEFAULT_BUMP: patch
