name: Testing stuff

on:
    push:
        branches:
            - main

env:
    # the below will be 'true'
    CONDITION: ${{ contains( join(toJson(github.event.commits.*.message),','), '#skip') }}
    # the below will be 'true'
    NEW_CONDITION: ${{ contains('kissa', 'ss') && contains('koira', 'ra') && contains('pretty long array of criteria to repeat in multiple places', 'crit') }}

jobs:
    a_test_job:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: github context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: commits
              env:
                  COMMITS: ${{ toJson(github.event.commits) }}
              run: echo "$COMMITS"
            - name: commit messages
              env:
                  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
              run: echo "$COMMIT_MESSAGES"
            - if: ${{ env.NEW_CONDITION == 'true' }}
              run: echo 'this step is executed'
            - if: ${{ env.NEW_CONDITION == 'false' }}
              run: echo 'this step will not be executed'

    condition_test_job:
        runs-on: ubuntu-24.04
        steps:
            - run: echo 'Valor de la condicion = github.env.CONDITION'
            - run: echo 'Valor de la condicion = $CONDITION'
            - if: ${{ contains( join(github.env.COMMIT_MESSAGES,','), '#skip') }} == 'true' }}
              run: echo 'condicion con ENV cumplida para el commit'
            - if: ${{ contains( join(github.env.COMMIT_MESSAGES,','), '#skip') }} == 'false' }}
              run: echo 'NO se cumple condicion con ENV para el commit'
            - if: ${{ contains( join(toJson(github.event.commits.*.message),','), '#skip') }} == 'true' }}
              run: echo 'condicion cumplida para el commit'
            - if: ${{ contains( join(toJson(github.event.commits.*.message),','), '#skip') }} == 'false' }}
              run: echo 'NO se cumple para el commit'
