name: Testing stuff

on:
    push:
        branches:
            - main

env:
    # the below will be 'true'
    CONDITION: ${{ contains( join(toJson(github.event.commits.*.message),','), '#skip') }}

jobs:
    a_test_job:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: github context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: commits
              env:
                  COMMITS: ${{ toJson(github.event.commits) }}
              run: echo "$COMMITS"
            - name: commit messages
              env:
                  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
              run: echo "$COMMIT_MESSAGES"

    condition_test_job:
        runs-on: ubuntu-24.04
        steps:
            - run: echo 'Valor de la condicion = github.env.CONDITION'
            - run: echo 'Valor de la condicion = $CONDITION'
            - if: ${{ contains( join(github.env.COMMIT_MESSAGES,','), '#skip') }} == 'true' }}
              run: echo 'condicion cumplida para el commit'
            - if: ${{ contains( join(github.env.COMMIT_MESSAGES,','), '#skip') }} == 'false' }}
              run: echo 'NO se cumple para el commit'
