name: Testing stuff

on:
    push:
        branches:
            - exercise_11_16

env:
    # the below will be 'true'
    CONDITION: ${{ contains( join(github.event.commits.*.message), '#skip') }}

jobs:
    a_test_job:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: github context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: commits
              env:
                  COMMITS: ${{ toJson(github.event.commits) }}
              run: echo "$COMMITS"
            - name: commit messages
              env:
                  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
              run: echo "$COMMIT_MESSAGES"
            - name: commit messages joined
              env:
                  COMMIT_MESSAGES_STR: ${{ join(github.event.commits.*.message) }}
              run: echo "$COMMIT_MESSAGES_STR"
            - name: validate commit messages joined
              run: echo "${{ contains( env.COMMIT_MESSAGES_STR, '#skip') }}"
            - if: ${{ contains( join(github.event.commits.*.message) , '#skip') == 'true' }}
              run: echo 'DIRECTO | condicion cumplida para el commit'
            - if: ${{ contains( join(github.event.commits.*.message), '#skip') == 'false' }}
              run: echo 'DIRECTO | NO se cumple para el commit'
            - if: ${{ contains( env.COMMIT_MESSAGES_STR, '#skip') == 'true' }}
              run: echo 'CON VARIABLE | condicion cumplida para el commit'
            - if: ${{ contains( env.COMMIT_MESSAGES_STR, '#skip') == 'false' }}
              run: echo 'CON VARIABLE | NO se cumple para el commit'
            - if: ${{ env.CONDITION == 'true' }}
              run: echo 'condicion cumplida para el commit'
            - if: ${{ env.CONDITION == 'false' }}
              run: echo 'NO se cumple para el commit'
    job_true_test:
        if: ${{ github.env.CONDITION == 'true' }}
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - run: echo "Se ejecutará job_true_test"
    # job_false_test:
    #   if: ${{ github.env.CONDITION == 'false' }}
    #   runs-on: ubuntu-24.04
    #   steps:
    #     - uses: actions/checkout@v4
    #     - run: echo "Se ejecutará job_false_test"
